/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js type tooling and kept in the scaffold so
// typecheck works before the first local dev run.
